spring:
  application:
    name: document_service

  profiles:
    active: local

  data:
    mongodb:
      host: localhost
      port: 27017
      database: document_service
      auto-index-creation: true

server:
  port: 5800

aws:
  region: ${S3_BUCKET_REGION}
  access-key: ${MINIO_USERNAME}
  secret-key: ${MINIO_PASSWORD}
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    endpoint: ${S3_BUCKET_ENDPOINT}

minio:
  webhook:
    secret-token: ${MINIO_SECRET_TOKEN}

jwt:
  signing_key: ${JWT_SIGNING_KEY}